"""Typed contracts shared by MALG agents and deterministic processing."""

from malg.core.models.account import (
    AccountCandidate,
    AccountFirmographics,
    AccountFitAssessment,
    AccountIdentity,
    AccountMatchRecord,
    AccountOperatingProfile,
    AccountProbeReport,
    AccountProfile,
    AccountRecord,
    AccountValidationAssessment,
    AccountValidationOutcome,
    CheckOutcome,
    CommunicationEndpointCandidate,
    ContactCandidate,
    DiscoveryMethod,
    EndpointKind,
    MailDomainProbeResult,
    UrlProbeResult,
    ValidationCheck,
)
from malg.core.models.campaign import CampaignCandidate
from malg.core.models.evidence import EvidenceItem, EvidenceKind, EvidenceStrength, SourceType
from malg.core.models.icp import (
    ICPBatchResult,
    ICPBuyerSignals,
    ICPEntryPlan,
    ICPEvidenceAssessment,
    ICPIdentity,
    ICPOperatingFoundation,
    ICPRejection,
    ICPResult,
    ICPSegmentFoundation,
)
from malg.core.models.jobs import (
    AccountResearchJobRequest,
    CampaignResearchJobRequest,
    ICPResearchJobRequest,
    ResearchJobKind,
    ResearchJobRecord,
    ResearchJobRequest,
    ResearchJobStatus,
)

__all__ = [
    "AccountCandidate",
    "AccountFirmographics",
    "AccountFitAssessment",
    "AccountIdentity",
    "AccountMatchRecord",
    "AccountOperatingProfile",
    "AccountProbeReport",
    "AccountProfile",
    "AccountRecord",
    "AccountResearchJobRequest",
    "AccountValidationAssessment",
    "AccountValidationOutcome",
    "CampaignCandidate",
    "CampaignResearchJobRequest",
    "CheckOutcome",
    "CommunicationEndpointCandidate",
    "ContactCandidate",
    "DiscoveryMethod",
    "EndpointKind",
    "EvidenceItem",
    "EvidenceKind",
    "EvidenceStrength",
    "ICPBatchResult",
    "ICPBuyerSignals",
    "ICPEntryPlan",
    "ICPEvidenceAssessment",
    "ICPIdentity",
    "ICPOperatingFoundation",
    "ICPRejection",
    "ICPResearchJobRequest",
    "ICPResult",
    "ICPSegmentFoundation",
    "MailDomainProbeResult",
    "ResearchJobKind",
    "ResearchJobRecord",
    "ResearchJobRequest",
    "ResearchJobStatus",
    "SourceType",
    "UrlProbeResult",
    "ValidationCheck",
]
